### ISSUE TITLE
Let GDM timeout and it changes to a blank screen where there is no way to recover

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/gdm3#1]
Launchpad bug:

https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1850727

It seems to only happen once the Pop PPA is added and then installs our GDM package. Stock Ubuntu 18.04 doesn't have this issue. 

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
apt policy gdm3
gdm3:
Installed: 3.28.3-0ubuntu18.04.5pop1~1551986836~18.04~d21ecd7
Candidate: 3.28.3-0ubuntu18.04.5pop1~1551986836~18.04~d21ecd7~dev
Version table:
*** 3.28.3-0ubuntu18.04.5pop1~1551986836~18.04~d21ecd7 100
100 /var/lib/dpkg/status
3.28.3-0ubuntu18.04.5pop1~1551986836~18.04~d21ecd7~dev 1001
1001 http://ppa.launchpad.net/system76-dev/stable/ubuntu bionic/main amd64 Packages
3.28.3-0ubuntu18.04.4 500
500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
3.28.0-0ubuntu1 500
500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
apt policy gnome-shell
gnome-shell:
Installed: 3.28.4-0ubuntu18.04.1
Candidate: 3.28.4-0ubuntu18.04.1
Version table:
*** 3.28.4-0ubuntu18.04.1 500
500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
100 /var/lib/dpkg/status
3.28.3+git20190124-0ubuntu18.04.2 500
500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
3.28.1-0ubuntu2 500
500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

Steps to recreate:

Power on system - NOT LIVE DISK.
It gets to the ubuntu login screen.
Do NOT login and stay at this screen until the screen goes blank.
try to wake screen and unable to.
only course of action here is to hard power off.

**Comment by bflanagin** [comment]
Not seeing this in newer versions of Pop or Ubuntu. Is this still an issue @ahoneybun

**Comment by ahoneybun** [comment]
I haven't tested it in a while so most likely it has been fixed.
