### ISSUE TITLE
GDM login screen on v22.04 is nonresponsive after screen blank, switching TTYs fixes it

### ISSUE THREAD

**Issue by wagnerck** [pop-os/gdm3#16]
On Pop!OS beta v22.04, the GDM login screen is non-responsive after waking up from having the screen turned off due to inactivity. I have replicated this on both a live system (an old HP EliteBook 8460p that I use for testing) and in a VM (via `virt-manager`). Both systems were v21.10 installs upgraded to v22.04 via `pop-upgrade`. I've attached videos of both.

If the system is left at the GDM login screen long enough for the screen to turn off, it will not respond to mouse activity or keyboard input after waking the screen. The mouse cursor moves but none of the screen elements react, keyboard activity is ignored, and logging in is impossible.

Switching a different TTY by hitting Ctrl-Alt-F3 works. When you go back to GDM by hitting Ctrl-Alt-F1 it is once again responsive to keyboard and mouse activity, and login works normally.

This seems like a fairly common scenario, where you turn the system on and wait for it to finish booting, but don't come back before the screen turns off due to inactivity. This happened to me several times before I realized what was going on. It happens on initial startup before the first login, but will also happen if you log out completely and leave the system idle.

https://user-images.githubusercontent.com/96320715/161557805-8a7a49aa-6d1c-45dd-b373-9f9e5de31a8b.mp4

![GDM freezes after screen blank - VM](https://user-images.githubusercontent.com/96320715/161559599-13bd9e83-6848-446e-b71a-f3acb31c61c8.gif)

**Comment by wagnerck** [comment]
It appears that an update has fixed this in the few hours since I submitted it and this afternoon. I noticed that it was fixed on the laptop after running updates, but the VM did not have those updates and was still experiencing the problem. I ran the following upgrade:
```
ckw@pop-os:~$ sudo aptitude full-upgrade 
The following NEW packages will be installed:
  fwupd-signed{a} fwupd-unsigned{a} libflashrom1{a} libftdi1-2{a} 
  libfwupdplugin5{a} 
The following packages will be REMOVED:
  libfwupdplugin1{u} 
The following packages will be upgraded:
  apt apt-utils build-essential dbus dbus-user-session dbus-x11 fuse3 fwupd 
  gdisk gettext-base gir1.2-javascriptcoregtk-4.0 gir1.2-mutter-10 
  gir1.2-webkit2-4.0 gnome-online-accounts gnome-settings-daemon 
  gnome-settings-daemon-common gnome-shell gnome-shell-common 
  gnome-shell-extension-prefs intel-media-va-driver libapt-pkg6.0 
  libdbus-1-3 libfuse3-3 libfwupd2 libgee-0.8-2 libgoa-1.0-0b 
  libgoa-1.0-common libgoa-backend-1.0-1 libjavascriptcoregtk-4.0-18 
  liblzo2-2 libmutter-10-0 libproxy1-plugin-gsettings 
  libproxy1-plugin-networkmanager libproxy1v5 libwacom-bin libwacom-common 
  libwacom9 libwebkit2gtk-4.0-37 libyelp0 lp-solve mutter mutter-common 
  net-tools pop-cosmic pop-desktop printer-driver-brlaser psmisc rsync 
  usb.ids xauth xwayland yelp 
The following packages are RECOMMENDED but will NOT be installed:
  pulseaudio pulseaudio:i386 yaru-theme-gnome-shell 
52 packages upgraded, 5 newly installed, 1 to remove and 0 not upgraded.
Need to get 41.1 MB of archives. After unpacking 2,125 kB will be used.
Do you want to continue? [Y/n/?]
```
and after rebooting the VM, the problem went away. Not sure which of these updates was the fix, but if no one else can replicate the problem, this is safe to close.

@mmstick  If you fixed this in four hours, I'm impressed.

**Comment by mmstick** [comment]
I haven't yet looked into this one.

**Comment by wagnerck** [comment]
Well, then I guess it was from something upstream from Ubuntu? It appears to be fixed regardless of who did it.

**Comment by mmstick** [comment]
We can re-open if it happens again
